import {devices,breakpoints,boundaries,checklist,statuses} from './catalog.js';
import {defaults,readState,writeState,clearState,normalizeURL,dimension,newView,record} from './storage.js';
import {ViewManager,el} from './views.js';
import {report,markdown,download,capture} from './reports.js';
import {runnerConfig,parseResult} from './adapters.js';
const $=id=>document.getElementById(id);let state=readState(),external=null;
const message=text=>{$('message').textContent=text;};
const save=()=>{if(!writeState(state))message('No se pudo guardar localmente. Exporta la revisión para conservarla.');};
const current=()=>state.views[state.active];
const byId=id=>state.views.find(v=>v.id===id);
const manager=new ViewManager($('views'),{
 select(id){state.active=state.views.findIndex(v=>v.id===id);render();},
 rotate(id){rotate(byId(id));render();},
 remove(id){state.views=state.views.filter(v=>v.id!==id);state.active=Math.min(state.active,state.views.length-1);render();},
 resize(id,w,h){const v=byId(id);v.width=w;v.height=h;v.name='Viewport personalizado';v.source='Redimensionamiento manual';v.dpr=null;v.presetId=undefined;v.orientation=w>h?'horizontal':'vertical';state.active=state.views.indexOf(v);manager.render(state);$('width').value=w;$('height').value=h;},
 resizeEnd(){render();}
});
function rotate(v){record(state,v);const p=devices.find(d=>d.id===v.presetId);if(p&&v.width===p.width&&v.height===p.height&&p.landscape){v.width=p.landscape.width;v.height=p.landscape.height;}else if(p?.landscape&&v.width===p.landscape.width&&v.height===p.landscape.height){v.width=p.width;v.height=p.height;}else [v.width,v.height]=[v.height,v.width];v.orientation=v.width>v.height?'horizontal':'vertical';}
function applyPreset(p){const v=current();record(state,v);Object.assign(v,{name:p.name,width:p.width,height:p.height,dpr:p.dpr??null,source:p.source||'Preset personalizado guardado',presetId:p.id,orientation:p.width>p.height?'horizontal':'vertical'});render();}
function render(){state.views.forEach(v=>record(state,v));$('url').value=state.url;$('open').href=state.url;$('width').value=current().width;$('height').value=current().height;$('zoom').value=state.zoom;$('frame').checked=!!current().frame;$('sidebar').hidden=!state.sidebar;document.querySelector('.lab-layout').classList.toggle('collapsed',!state.sidebar);$('toggle-sidebar').setAttribute('aria-expanded',String(state.sidebar));$('view-count').textContent=`${state.views.length} / 4 vistas`;$('add-view').disabled=state.views.length===4;manager.render(state);renderChecklist();renderDevices();save();}
function renderDevices(){const q=$('search').value.toLocaleLowerCase(),fav=$('only-favorites').checked;$('devices').replaceChildren();let group='';for(const p of devices){if(!p.name.toLocaleLowerCase().includes(q)&&!p.group.toLocaleLowerCase().includes(q)||fav&&!state.favorites.includes(p.id))continue;if(group!==p.group){group=p.group;$('devices').append(el('h3',{class:'device-group'},group));}const row=el('div',{class:'device-row'}),use=el('button'),txt=el('span',{},p.name);txt.append(el('small',{},`${p.width} × ${p.height} · DPR ${p.dpr}`));use.append(txt);use.onclick=()=>applyPreset(p);const star=el('button',{'aria-label':`Favorito: ${p.name}`,'aria-pressed':String(state.favorites.includes(p.id))},state.favorites.includes(p.id)?'★':'☆');star.onclick=()=>{state.favorites=state.favorites.includes(p.id)?state.favorites.filter(x=>x!==p.id):[...state.favorites,p.id];renderDevices();save();};row.append(use,star);$('devices').append(row);}$('custom-devices').replaceChildren();for(const p of state.custom){const row=el('div',{class:'device-row'}),use=el('button',{},`${p.name} · ${p.width} × ${p.height}`),remove=el('button',{'aria-label':`Eliminar preset ${p.name}`},'×');use.onclick=()=>applyPreset(p);remove.onclick=()=>{state.custom=state.custom.filter(x=>x.id!==p.id);renderDevices();save();};row.append(use,remove);$('custom-devices').append(row);}}
function updateRecord(){const r=record(state,current());r.updatedAt=new Date().toISOString();save();}
function renderChecklist(){const v=current(),r=record(state,v);$('review-title').textContent=`Checklist · vista ${state.active+1} · ${v.name}`;$('review-context').textContent=`${v.width} × ${v.height} CSS px · ${state.url}`;$('checklist').replaceChildren();for(const [id,label,hint] of checklist){const row=el('div',{class:'review-row'}),description=el('div');description.append(el('strong',{},label),el('small',{},hint));const select=el('select',{'aria-label':`Estado: ${label}`});statuses.forEach(s=>select.append(el('option',{value:s},s)));select.value=r.checks[id]?.state||'Pendiente';const note=el('input',{'aria-label':`Observación: ${label}`,placeholder:'Observación…',maxlength:'2000'});note.value=r.checks[id]?.note||'';const update=()=>{r.checks[id]={state:select.value,note:note.value,assignedBy:'user',date:new Date().toISOString()};updateRecord();};select.onchange=update;note.oninput=update;row.append(description,select,note);$('checklist').append(row);}$('notes').value=r.notes||'';for(const key of ['browser','os','device','kind','date','evidence'])$('real-'+key).value=r.real?.[key]||(key==='kind'?'unknown':'');}
$('url-form').onsubmit=e=>{e.preventDefault();try{state.views.forEach(v=>record(state,v));state.url=normalizeURL($('url').value);render();message('URL aplicada a todas las vistas. La navegación interna sigue siendo independiente.');}catch(err){message(err.message);}};
$('reload').onclick=()=>manager.reload();
$('dimensions').onsubmit=e=>{e.preventDefault();try{applyPreset({name:'Viewport personalizado',width:dimension($('width').value),height:dimension($('height').value,3840)});}catch(err){message(err.message);}};
$('rotate').onclick=()=>{rotate(current());render();};$('frame').onchange=()=>{current().frame=$('frame').checked;render();};
$('toggle-sidebar').onclick=()=>{state.sidebar=!state.sidebar;render();};$('zoom').onchange=()=>{state.zoom=$('zoom').value;render();};
$('add-view').onclick=()=>{if(state.views.length>=4)return;const v=current(),n=newView(v.width,v.height);Object.assign(n,{name:v.name,dpr:v.dpr,source:v.source,presetId:v.presetId,frame:v.frame});state.views.push(n);state.active=state.views.length-1;render();};
for(const [label,width] of breakpoints){const b=el('button',{},label);b.onclick=()=>applyPreset({name:label,width,height:current().height});$('breakpoints').append(b);}
for(const [a,b] of boundaries){const button=el('button',{},`${a} / ${b}`);button.onclick=()=>{if(state.views.length>2){message('Deja dos espacios libres para añadir esta pareja (máximo 4 vistas).');return;}state.views.push(newView(a,current().height),newView(b,current().height));state.active=state.views.length-2;render();message(`Añadidas vistas de ${a} y ${b} CSS px.`);};$('boundaries').append(button);}
$('search').oninput=renderDevices;$('only-favorites').onchange=renderDevices;
$('custom-form').onsubmit=e=>{e.preventDefault();const name=$('custom-name').value.trim();if(!name)return;if(state.custom.length>=50){message('Máximo 50 presets; elimina uno antes de añadir otro.');return;}state.custom.push({id:crypto.randomUUID(),name,width:current().width,height:current().height,source:'Preset personalizado guardado'});$('custom-name').value='';renderDevices();save();message('Preset guardado.');};
$('notes').oninput=()=>{record(state,current()).notes=$('notes').value;updateRecord();};for(const key of ['browser','os','device','kind','date','evidence'])$('real-'+key).oninput=()=>{const r=record(state,current());r.real??={};r.real[key]=$('real-'+key).value;r.real.assignedBy='user';updateRecord();};
$('reset').onclick=()=>{if(!confirm('¿Restablecer esta revisión? Exporta primero las observaciones que quieras conservar. Se mantienen favoritos y presets.'))return;state={...defaults(),favorites:state.favorites,custom:state.custom};external=null;$('runner-results').replaceChildren();render();message('Revisión restablecida.');};
$('clear-data').onclick=()=>{if(!confirm('¿Borrar revisión, favoritos, presets y preferencias guardados?'))return;const ok=clearState();state=defaults();external=null;$('runner-results').replaceChildren();$('search').value='';$('only-favorites').checked=false;render();clearState();message(ok?'Datos guardados eliminados.':'El navegador no permite borrar el almacenamiento.');};
function mode(engine){$('responsive-panel').hidden=engine;$('engines-panel').hidden=!engine;$('responsive-mode').setAttribute('aria-pressed',String(!engine));$('engines-mode').setAttribute('aria-pressed',String(engine));if(!engine)manager.fit();}
$('responsive-mode').onclick=()=>mode(false);$('engines-mode').onclick=()=>mode(true);
$('runner-config').onclick=()=>download('responsive-lab-config.json',JSON.stringify(runnerConfig(state),null,2),'application/json');
$('import-result').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>2000000)throw Error('Máximo 2 MB.');external=parseResult(await file.text());$('runner-results').replaceChildren(el('h3',{},'Informe importado · no es una ejecución en esta página'),el('pre',{},JSON.stringify(external,null,2)));message(`Informe importado: ${external.date}. URL: ${external.url}`);}catch(err){message(err.message);}finally{e.target.value='';}};
$('export-json').onclick=()=>download('responsive-lab-review.json',JSON.stringify(report(state,manager,external),null,2),'application/json');$('export-md').onclick=()=>download('responsive-lab-review.md',markdown(report(state,manager,external)),'text/markdown');
$('capture').disabled=!navigator.mediaDevices?.getDisplayMedia;if($('capture').disabled)$('capture-help').textContent='Captura deshabilitada: este navegador no expone selección de pantalla. Usa una captura del sistema o el runner.';$('capture').onclick=async()=>{try{await capture();message('Captura de la superficie seleccionada descargada.');}catch(err){message(err.name==='NotAllowedError'?'Captura cancelada o no autorizada por el navegador.':err.message);}};
$('demo').onclick=e=>{e.preventDefault();state.url=$('demo').href+'?lab=demo#intro';render();};
render();
