export const KEY='webflow-responsive-lab-v1';
export function normalizeURL(raw){const value=String(raw).trim();if(!value)throw Error('Introduce una URL.');const u=new URL(/^[a-z][a-z\d+.-]*:/i.test(value)?value:'https://'+value);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error('Usa una URL HTTP(S), sin credenciales.');return u.href;}
export function dimension(value,max=3840){const n=Number(value);if(!Number.isInteger(n)||n<240||n>max)throw Error(`Dimensión permitida: 240–${max} CSS px.`);return n;}
export function newView(width=390,height=664){return {id:crypto.randomUUID(),name:'Viewport personalizado',width,height,dpr:null,source:'Dimensiones elegidas por el usuario',orientation:width>height?'horizontal':'vertical',frame:false,records:{}};}
export function defaults(){return {version:1,url:new URL('./fixtures/layout.html?lab=demo#intro',import.meta.url).href,views:[newView()],active:0,zoom:'fit',sidebar:true,favorites:[],custom:[]};}
export function readState(){try{const s=JSON.parse(localStorage.getItem(KEY));if(!s||s.version!==1)return defaults();s.url=normalizeURL(s.url);if(!Array.isArray(s.views)||!s.views.length||s.views.length>4)throw Error();s.views.forEach(v=>{dimension(v.width);dimension(v.height,2560);if(typeof v.id!=='string')throw Error();v.records=v.records&&typeof v.records==='object'?v.records:{};});s.active=Math.min(Math.max(0,Number(s.active)||0),s.views.length-1);s.zoom=['fit','0.25','0.5','0.75','1','1.25'].includes(s.zoom)?s.zoom:'fit';s.favorites=Array.isArray(s.favorites)?s.favorites.filter(x=>typeof x==='string'):[];s.custom=Array.isArray(s.custom)?s.custom.filter(x=>Number.isInteger(x.width)&&x.width>=240&&x.width<=3840&&Number.isInteger(x.height)&&x.height>=240&&x.height<=2560).slice(0,50):[];return s;}catch{return defaults();}}
export function writeState(state){try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch{return false;}}
export function clearState(){try{localStorage.removeItem(KEY);return true;}catch{return false;}}
export function recordKey(state,v){return JSON.stringify([state.url,v.width,v.height,v.name]);}
export function record(state,v){const k=recordKey(state,v);return v.records[k]??=( {url:state.url,width:v.width,height:v.height,preset:v.name,orientation:v.orientation,dprReference:v.dpr??null,source:v.source,createdAt:new Date().toISOString(),checks:{},notes:'',real:{}} );}
