export function el(tag,attrs={},text){const n=document.createElement(tag);for(const [k,v] of Object.entries(attrs)){if(k==='class')n.className=v;else n.setAttribute(k,v);}if(text!==undefined)n.textContent=text;return n;}
export class ViewManager{
 constructor(root,callbacks){this.root=root;this.callbacks=callbacks;this.cards=new Map();this.observer=new ResizeObserver(()=>this.fit());this.observer.observe(root);}
 render(state){this.state=state;this.root.classList.toggle('single',state.views.length===1);for(const [id,c] of this.cards){if(!state.views.some(v=>v.id===id)){clearTimeout(c.timer);c.card.remove();this.cards.delete(id);}}
 state.views.forEach((v,index)=>{let c=this.cards.get(v.id);if(!c){c=this.create(v);this.cards.set(v.id,c);this.root.append(c.card);}c.v=v;c.card.classList.toggle('active',index===state.active);c.select.textContent=`${index+1}. ${v.name}`;c.select.setAttribute('aria-pressed',String(index===state.active));c.remove.disabled=state.views.length===1;c.iframe.title=`Vista ${index+1}: ${v.name} (${v.width} × ${v.height})`;c.iframe.width=String(v.width);c.iframe.height=String(v.height);c.iframe.style.width=v.width+'px';c.iframe.style.height=v.height+'px';c.screen.style.width=v.width+'px';c.screen.style.height=v.height+'px';c.screen.classList.toggle('decorative',!!v.frame);c.source.replaceChildren(document.createTextNode(`DPR de referencia: ${v.dpr??'—'} · ${v.orientation} · `));if(/^https:\/\//.test(v.source||''))c.source.append(el('a',{href:v.source,target:'_blank',rel:'noopener noreferrer'},'Fuente del preset'));else c.source.append(document.createTextNode(v.source||'Personalizado'));if(c.requested!==state.url)this.navigate(c,state.url);});this.fit();}
 create(v){const card=el('article',{class:'viewport-card'}),head=el('div',{class:'view-header'}),select=el('button',{class:'select-view'}),rotate=el('button',{'aria-label':'Girar esta vista'},'↻'),remove=el('button',{'aria-label':'Eliminar esta vista'},'×');head.append(select,rotate,remove);const metrics=el('div',{class:'view-metrics'}),stage=el('div',{class:'stage'}),sizer=el('div',{class:'sizer'}),screen=el('div',{class:'screen'}),iframe=el('iframe',{referrerpolicy:'strict-origin-when-cross-origin',allow:'fullscreen'}),handle=el('button',{class:'resize-handle','aria-label':'Redimensionar vista: arrastra o usa las flechas','title':'Arrastra; flechas: 10 px, Shift: 1 px'},'↘');screen.append(iframe);sizer.append(screen,handle);stage.append(sizer);const help=el('div',{class:'view-help'}),status=el('p',{'aria-live':'polite'}),details=el('details'),summary=el('summary',{},'¿Vista vacía o sitio no visible?'),direct=el('a',{target:'_blank',rel:'noopener noreferrer'},'Abrir la URL directamente ↗');details.append(summary,el('p',{},'La carga puede estar bloqueada por políticas del sitio, red, autenticación o contenido mixto. El navegador no permite confirmar la causa en un iframe externo. No se eliminan protecciones ni se usan proxies.'),direct);help.append(status,details);const source=el('div',{class:'view-source'});card.append(head,metrics,stage);const c={card,select,remove,metrics,stage,sizer,screen,iframe,handle,status,direct,source,v};select.onclick=()=>this.callbacks.select(v.id);rotate.onclick=()=>this.callbacks.rotate(v.id);remove.onclick=()=>this.callbacks.remove(v.id);iframe.addEventListener('load',()=>{clearTimeout(c.timer);this.inspect(c);});iframe.addEventListener('error',()=>{clearTimeout(c.timer);status.textContent='Carga no verificable. Abre la URL o consulta la ayuda.';});handle.onpointerdown=e=>{if(e.button!==0)return;e.preventDefault();handle.setPointerCapture(e.pointerId);const start={x:e.clientX,y:e.clientY,w:c.v.width,h:c.v.height,scale:c.scale};card.classList.add('dragging');handle.onpointermove=m=>{this.callbacks.resize(v.id,Math.max(240,Math.min(3840,Math.round(start.w+(m.clientX-start.x)/start.scale))),Math.max(240,Math.min(3840,Math.round(start.h+(m.clientY-start.y)/start.scale))));};const stop=()=>{handle.onpointermove=null;card.classList.remove('dragging');this.callbacks.resizeEnd();};handle.onpointerup=stop;handle.onpointercancel=stop;};handle.onkeydown=e=>{const delta=e.shiftKey?1:10;let w=c.v.width,h=c.v.height;if(e.key==='ArrowRight')w+=delta;else if(e.key==='ArrowLeft')w-=delta;else if(e.key==='ArrowDown')h+=delta;else if(e.key==='ArrowUp')h-=delta;else return;e.preventDefault();this.callbacks.resize(v.id,Math.max(240,Math.min(3840,w)),Math.max(240,Math.min(3840,h)));this.callbacks.resizeEnd();};return c;}
 navigate(c,url){clearTimeout(c.timer);c.requested=url;c.direct.href=url;c.status.textContent='Cargando… la visibilidad del contenido debe comprobarse.';c.iframe.src=url;c.timer=setTimeout(()=>{c.status.textContent='Carga no verificable tras 10 s. Puedes interactuar si el sitio es visible o abrirlo directamente.';},10000);}
 inspect(c){try{const doc=c.iframe.contentDocument;if(!doc||!doc.documentElement||doc.URL==='about:blank')throw Error();c.status.textContent='Documento accesible. Revisa visualmente el contenido y sus interacciones.';c.actualURL=doc.URL;}catch{c.actualURL=null;c.status.textContent='Evento de carga recibido · contenido externo no verificable. Comprueba que el sitio se ve; este evento no confirma éxito.';}}
 fit(){for(const c of this.cards.values()){const {width,height}=c.v;const available=Math.max(50,c.stage.clientWidth-38);const scale=this.state.zoom==='fit'?Math.min(1,available/width):Number(this.state.zoom);c.scale=scale;c.screen.style.transform=`scale(${scale})`;c.sizer.style.width=width*scale+'px';c.sizer.style.height=height*scale+'px';c.metrics.textContent=`${width} × ${height} CSS px · escala ${Math.round(scale*100)}% · ${c.v.orientation}`;}}
 reload(){for(const c of this.cards.values())this.navigate(c,this.state.url);}
 evidence(id){const c=this.cards.get(id);if(!c)return {};let actualURL=null;try{actualURL=c.iframe.contentWindow.location.href;}catch{}return {requestedURL:c.requested,finalURL:actualURL,visualScale:c.scale,iframeReadability:actualURL?'same-origin':'unverified-external'};}
}
